# Generated by Django 4.0.5 on 2022-06-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='levels',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Order Confirmed')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, choices=[('WS', 'Windsor'), ('CG', 'Calgery'), ('MR', 'Montreal'), ('VC', 'Vancouver')], default='WS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[(0, 'Development'), (1, 'Business'), (2, 'IT & Software'), (3, 'Finance & Accounting'), (4, 'Health&Fitness')], max_length=200),
        ),
    ]
