# Generated by Django 4.0.5 on 2022-06-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_order_levels_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[(6, 'Development'), (1, 'Business'), (2, 'IT & Software'), (3, 'Finance & Accounting'), (4, 'Health&Fitness')], max_length=200),
        ),
    ]
