# Generated by Django 4.0.5 on 2022-06-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_alter_order_levels_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='stage',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
