# Generated by Django 4.0.5 on 2022-08-04 18:29

import Myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_order_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[Myapp.models.validate_price]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.IntegerField(choices=[(1, 'Business'), (2, 'IT & Software'), (3, 'Finance & Accounting'), (4, 'Health&Fitness'), (6, 'Development')]),
        ),
    ]
